apiVersion: v1
kind: ConfigMap
metadata:
  name: blackbox-exporter
  namespace: monitoring
data:
  blackbox.yml: |
    modules:
      http_2xx:
        prober: http
        http:
          tls_config:
            insecure_skip_verify: true
    
      http_post_2xx:
        prober: http
        http:
          method: POST
          tls_config:
            insecure_skip_verify: true
    
      tcp_connect:
        prober: tcp
    
      dns:
        prober: dns
        dns:
          query_name: "www.prometheus.io"
          query_type: "A"
  
      dns-tcp:
        prober: dns
        dns:
          transport_protocol: "tcp"
          query_name: "www.prometheus.io"
          query_type: "A"
